wandb_version: 1

Iteration:
  desc: null
  value: 5000
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1762282541
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
batch_real:
  desc: null
  value: 256
batch_syn:
  desc: null
  value: null
batch_train:
  desc: null
  value: 256
buffer_path:
  desc: null
  value: /data/hushuhao-20251019/projects/MTT_FD/buffers
canvas_samples:
  desc: null
  value: 1
canvas_size:
  desc: null
  value: 2
data_path:
  desc: null
  value: /data/hushuhao-20251019/projects/MTT_FD/data
dataset:
  desc: null
  value: CIFAR100
dc_aug_param:
  desc: null
  value: null
device:
  desc: null
  value: cuda
dsa:
  desc: null
  value: true
dsa_param:
  desc: null
  value: <utils.ParamDiffAug object at 0x7fbd00f01a60>
dsa_strategy:
  desc: null
  value: color_crop_cutout_flip_scale_rotate
epoch_eval_train:
  desc: null
  value: 1000
eval_it:
  desc: null
  value: 100
eval_mode:
  desc: null
  value: S
expert_epochs:
  desc: null
  value: 3
force_save:
  desc: null
  value: false
im_size:
  desc: null
  value:
  - 32
  - 32
ipc:
  desc: null
  value: 48
load_all:
  desc: null
  value: false
lr_img:
  desc: null
  value: 1000.0
lr_init:
  desc: null
  value: 0.01
lr_lr:
  desc: null
  value: 1.0e-05
lr_teacher:
  desc: null
  value: 0.01
max_experts:
  desc: null
  value: null
max_files:
  desc: null
  value: null
max_start_epoch:
  desc: null
  value: 20
model:
  desc: null
  value: ConvNet
no_aug:
  desc: null
  value: false
num_eval:
  desc: null
  value: 5
pix_init:
  desc: null
  value: real
res:
  desc: null
  value: 128
subset:
  desc: null
  value: imagenette
syn_steps:
  desc: null
  value: 20
texture:
  desc: null
  value: false
zca:
  desc: null
  value: true
zca_trans:
  desc: null
  value: ZCAWhitening()
